name: logging_generator
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  analyzer: ^5.13.0
  build: ^2.4.0
  code_builder: ^4.4.0
  dart_style: ^2.3.1
  source_gen: ^1.3.2
  logging_utils:
    path: ../logging_utils

dev_dependencies:
  build_runner: ^2.4.4
  lints: ^2.1.0
  test: ^1.24.3
