name: logging_utils
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  logging: ^1.2.0
  ansi_codes: ^0.1.1
  # TODO: Move this back to dev dependencies
  test: ^1.24.3


dev_dependencies:
  lints: ^2.1.0
