name: logging_utils
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  ansi_codes: ^0.1.1
  logging: ^1.2.0
  logging_appenders: ^1.1.0
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
